language: ruby
rvm: 1.9.3
bundler_args: --without development production
before_script:
- sh -e /etc/init.d/xvfb start
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake spec
- bundle exec rake cucumber
