language: ruby
sudo: false
rvm:
- 1.9.3
before_script:
- sh -e /etc/init.d/xvfb start
script:
- bundle exec rake --trace db:migrate
- bundle exec rake ci
- restart
deploy:
  provider: heroku
  api_key:
    secure: UlMxCM1TTbDExJpUTQ6icdAVrOEYkGBBvdKfJlficbGvkWmmClC7RISkGF2bIBxOICLvJ59y6vdG0MehVdpf2OSTv3EWhcnPrzRVxmtQlJ49IobCXaPJlOSqKiVkotv9EM1vljrDfiVniupvet9DI6NGLG7j1OTasXQUjhHvpfA=
  app:
    develop: keventer-test
    master: keventer
