language: ruby
rvm:
- 1.9.3

env:
- DB=postgresql

before_script:
- sh -e /etc/init.d/xvfb start
- psql -c 'create database eventer_test' -U postgres

script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
  - RAILS_ENV=test bundle exec rake --trace db:test:prepare
  - RAILS_ENV=test bundle exec rake spec