language: ruby
rvm:
- 1.9.3
before_script:
- sh -e /etc/init.d/xvfb start
script:
- bundle exec rake --trace db:migrate
- bundle exec rake ci
deploy:
  provider: heroku
  api_key:
    secure: JWnb0NtN18H4gttHyeQ5VWfnloHled39gQ+lYNSjEoCs7AiaWT+MV2jPYsxy7HpT8SYENAnbgpPwZ106DSEoXMrTCEEGvI0mDYiXvt/oP/dgfflr6/KRcpYswkXYUJJ42SGciBYjJZ5vEGbfSLITbx+HNsr+YLUJm3+i8/thet4=
  app:
    develop: keventer-test
    master: keventer
