language: ruby
rvm:
- 1.9.3
env:
- DB=sqlite
before_script:
- sh -e /etc/init.d/xvfb start
script:
- export RAILS_ENV=test
- bundle exec rake db:migrate test
- bundle exec rake db:test:prepare
- bundle exec rake spec