language: ruby
rvm:
- 1.9.3
bundler_args: --without development production
env:
- DB=sqlite
before_script:
- sh -e /etc/init.d/xvfb start
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- RAILS_ENV=test bundle exec rake spec
