version: "3"
services:
  eventer:
    image: ruby:2.1.8
    container_name: eventer
    ports:
      - '3000:3000'
    volumes:
      - C:\Users\User\Development\code\kleer\eventer:/home/eventer
    tty: true